version: '3.8'

services:
  orderservice:
    build: .
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      # - MONGO_URI=mongodb://mongo:27017/orderdb
      - MONGO_URI=mongodb://admin:admin@host.docker.internal:27017
      - USER_SERVICE_URL=http://host.docker.internal:4000
      - JWT_SECRET=your_secret_key
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: order-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
