version: '3.8'

services:
  orderservice:
    build: .
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://admin:admin@host.docker.internal:27017
    image: ashish010598/order-service:latest

